services:
  sub-store:
    image: xream/sub-store:latest
    container_name: sub-store
    restart: unless-stopped
    environment:
      SUB_STORE_CORS_ALLOWED_ORIGINS: "*"
      SUB_STORE_FRONTEND_BACKEND_PATH: /sub-store
    ports:
      - "25600:3001"
    volumes:
      - ./data:/opt/app/data