services:
  hermes:
    build:
      context: .
      dockerfile: Dockerfile.hermes
      pull: true
    image: hermes-agent-with-path:latest
    pull_policy: build
    container_name: hermes
    restart: unless-stopped
    volumes:
      - /Volumes/UrineBag/Docker/hermes/hermes-data:/opt/data
      - /Volumes/UrineBag/Docker/hermes/hermes-home:/hermes-home
    ports:
      - "8642:8642"
      - "9119:9119"
    environment:
      TZ: Asia/Shanghai
      HERMES_DASHBOARD: "1"
      HERMES_DASHBOARD_TUI: "1"
      API_SERVER_ENABLED: "true"
      API_SERVER_HOST: "0.0.0.0"
      API_SERVER_KEY: hermes-agent
      API_SERVER_CORS_ORIGINS: "*"
    command: gateway run
